[package]
name = "crusty-com"
version = "0.1.0"
edition = "2021"
authors = ["henry-sm"]

[workspace]
# Corrected members: src/gui is not a rust crate. src/gui/src-tauri is.
members = [ "src/emu", "src/gui/src-tauri" ]

[dependencies]
emu = { path = "src/emu" }
gui_lib = { path = "src/gui/src-tauri" }
